const kelimeler = [
    "elma",
    "armut",
    "muz",
    "portakal",
    "otomobil",
    "kamyon",
    "motosiklet",
    "bisiklet",
    "uçak",
    "gemi",
    "tren",
    "otobüs",
    "traktör",
    "tırpan",
    "süt",
    "yoğurt",
    "peynir",
    "tereyağı",
    "kefir",
    "ayran",
    "krem peynir",
    "lor peyniri",
    "kaşar peyniri",
    "mozzarella peyniri",
    "domates",
    "salatalık",
    "biber",
    "patlıcan",
    "patates",
    "soğan",
    "sarımsak",
    "havuç",
    "bezelye",
    "fasulye",
    "tavuk",
    "hindi",
    "dana",
    "kuzu",
    "balık",
    "somon",
    "ton balığı",
    "sardalya",
    "uskumru",
    "alabalık",
    "ekmek",
    "simit",
    "poğaça",
    "mercimek",
    "nohut",
    "fasulye",
    "bezelye",
    "barbunya",
    "börülce",
    "bakla",
    "fındık",
    "ceviz",
    "badem",
    "fıstık",
    "Antep fıstığı",
    "kaju fıstığı",
    "kabak çekirdeği",
    "ay çekirdeği",
    "karabiber",
    "kırmızı biber",
    "pul biber",
    "kimyon",
    "kekik",
    "nane",
    "fesleğen",
    "biberiye",
    "defne yaprağı",
    "zerdeçal",
    "zeytinyağı",
    "ayçiçek yağı",
    "mısır yağı",
    "soya yağı",
    "tereyağı",
    "Hindistan cevizi yağı",
    "bal",
    "reçel",
    "pekmez",
    "tahin",
    "helva",
    "şekerleme",
    "kek",
    "kurabiye",
    "pasta",
    "dondurma",
  ];
  
  export default kelimeler;